[package]
name = "vodozemac"
version = "0.1.0"
edition = "2021"

[dependencies]
aes = "0.7.5"
arrayvec = "0.7.2"
base64 = "0.13.0"
block-modes = "0.8.1"
ed25519-dalek = { version = "1.0.1", default-features = false, features = ["rand"] }
hkdf = "0.12.0"
hmac = "0.12.0"
pkcs7 = "0.3.0"
prost = "0.9.0"
rand = "0.7"
sha2 = "0.10.0"
thiserror = "1.0.26"
x25519-dalek = "1.2.0"
zeroize = "1.3"

[dev-dependencies]
olm-rs = "2.2.0"
anyhow = "1.0.41"
