[package]
name = "vodozemac"
version = "0.1.0"
edition = "2021"

[dependencies]
ed25519-dalek = "1.0.1"
prost = "0.7.0"
rand = "0.7"
x25519-dalek = "1.1.1"
pkcs7 = "0.3.0"
zeroize = "1.3.0"
sha2 = "0.9.5"
hkdf = "0.11.0"
hmac = "0.11.0"
aes = "0.7.4"
base64 = "0.13.0"
block-modes = "0.8.1"
dashmap = "4.0.2"

[dev-dependencies]
olm-rs = "2.2"
