[package]
name = "vodozemac"
version = "0.1.0"
edition = "2021"

[dependencies]
ed25519-dalek = "1.0.1"
prost = "0.9.0"
rand = "0.7"
x25519-dalek = "1.2.0"
pkcs7 = "0.3.0"
zeroize = "1.3"
sha2 = "0.10.0"
hkdf = "0.12.0"
hmac = "0.12.0"
aes = "0.7.5"
base64 = "0.13.0"
block-modes = "0.8.1"
dashmap = "5.0.0"

[dev-dependencies]
olm-rs = "2.2.0"
