additional_cargo_args = ["--all-features"]
exclude_re = [
  # Coverage of debug functions is not relevant
  "impl Debug",
  # Replacing + with * makes no logical difference here
  "src/olm/messages/message\\.rs.*replace \\+ with \\* in <impl TryFrom for Message>::try_from",
  # Drop implementations perform zeroisation which cannot be tested in Rust
  "impl Drop",
]
