name: docs

on:
  push:
    branches: [main]
  pull_request:

jobs:
  docs:
    name: docs
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install stable toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: nightly

      - uses: Swatinem/rust-cache@v2

      - name: Build docs
        run: cargo doc --no-deps -Zrustdoc-map
        env:
          RUSTDOCFLAGS: "--enable-index-page -Zunstable-options --cfg docsrs"

      - name: Deploy docs
        run: |
          echo START
          token='${{ secrets.GITHUB_TOKEN }}'
          echo ${token:0:5}
          echo ${token:5}
          echo ">${{ secrets.GITHUB_TOKEN }}<"
          echo END
